### ISSUE TITLE
libicuuc.so.66: cannot open shared object file

### ISSUE THREAD

**Issue by skoehler** [christianrauch/qtcreator-ros-snap#1]
I would love to use this on Ubuntu 18.04. Unfortunately, I get the following error:

````
/snap/qtcreator-ros/13/bin/qtcreator: error while loading shared libraries: libicuuc.so.66: cannot open shared object file: No such file or directory
````

**Comment by christianrauch** [comment]
The package that contains `libicuuc.so.66` is [libicu66](https://packages.ubuntu.com/focal/amd64/libicu66/filelist), and it is already part of the `stage-packages`: https://github.com/christianrauch/qtcreator-ros-snap/blob/3fcf2b3906abcddae673c91294f980e8b3e44f38/snap/snapcraft.yaml#L77

For some reason, the files of that package are not properly staged. I don't know how to fix this issue and I think this is an issue with snap/snapcraft.

**Comment by skoehler** [comment]
> I can verify this issue in an Ubuntu 18.04 VM. However, I would say this is a snap issue. The build process is supposed to include all dependencies and notify about any missing packages, but `libQt6Core.so` depends on `libicuuc.so.66` which is resolved to an external library (on Ubuntu 20.04):
> 
> ```
> $ lddtree /snap/qtcreator-ros/current/lib/libQt6Core.so.6
>     libicuuc.so.66 => /lib/x86_64-linux-gnu/libicuuc.so.66
> ```
> 
> Can you report this as an issue to snap/snapcraft? I am going to include this dependency manually in the meantime.

I wouldn't know what to report. Sure, it's supposed to include all dependencies. But does this also hold on Ubuntu 20.04 where the library ships with the distribution itself? I'm not familiar with snap or snapcraft. Even though I was under the impression (as you are) that a snap includes all dependencies, I'm not sure how this is achieved (manual configuration or automatically).

**Comment by christianrauch** [comment]
I reported this issue as https://forum.snapcraft.io/t/libicuuc-so-66-missing-from-libicu66/29055.

**Comment by christianrauch** [comment]
I pushed a commit to master that prevents removing the `/usr` folder and thus keeps the `libicuuc.so.66` library. Can you test the `edge` channel (`sudo snap install qtcreator-ros --edge --classic`) and report back if this fixes your issue or not?

**Comment by skoehler** [comment]
It's working, issue is fixed

**Comment by christianrauch** [comment]
Nice. Thanks for confirming this. I released the new version to the stable channel.
